name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - 'backend'
  pull_request:
    branches: 
      - 'dev'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'backend'
      # Runs a single command using the runners shell
      - name: Change to server directory
        run: cd server

      # Runs a shell command which display current directory
      - name: Show current directory
        run: ls -lah

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          sudo apt install nodejs 
          nodejs -v
          sudo apt install npm
          sudo npm install 


  tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'dev'
      # Runs a single command using the runners shell
      - name: Change to server directory
        run: cd server

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          sudo apt install nodejs 
          nodejs -v
          sudo apt install npm
          sudo npm install 
  
      - name: Test run
        run: npm run dev