name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - 'backend'
  pull_request:
    branches: 
      - 'backend'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'backend'

      # Runs a shell command which display current directory
      - name: Show server directory
        run: |
          cd server
          ls -lah

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          cd server
          sudo apt install nodejs 
          nodejs -v
          sudo apt install npm
          sudo npm install 
          

  test_run:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'backend'

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          cd server
          sudo apt install nodejs 
          nodejs -v
          sudo apt install npm
          sudo npm install 
          sudo apt install -y --no-install-recommends postgresql-client
          sudo apt install postgresql -y postgresql-contrib
          sudo service postgresql start
          sudo -u postgres psql -c "create role admin with login SUPERUSER password 'admin';"
          sudo -u postgres createdb online_store 
  
      - name: Test run
        run: |
          cd server
          (npm run dev&)


  linter_check:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'backend'

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          cd server
          sudo apt install nodejs 
          nodejs -v
          sudo apt install npm
          sudo npm install 
  
      - name: Test run
        run: |
          cd server
          eslint ./

  unit_tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'backend'

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          cd server
          sudo apt install nodejs 
          nodejs -v
          sudo apt install npm
          sudo npm install 
  
      - name: Test run
        run: |
          cd server
          npm run test